defaults: &defaults
  redis_url: <%= ENV['REDIS_URL'] %>
  redis_namespace: <%= ENV['REDIS_NAMESPACE'] %>
  mailer:
    :host: <%= ENV['MAILER_HOST'] %>
    :from: <%= ENV['MAILER_FROM'] %>
  secret_key_base:  <%= ENV['SECRET_KEY_BASE'] %>
  favicon: <%= ENV['FAVICON_PATH'] %>
  ldap:
    :enabled: <%= ENV['LDAP_ENABLED'] %>
    :base: <%= ENV['LDAP_BASE'] %>
    :host: <%= ENV['LDAP_HOST'] %>
    :port: <%= ENV['LDAP_PORT'] %>
    :matched_value: <%= ENV['LDAP_MATCHED_VALUE'] %>
  ses_address: <%= ENV['SES_ADDRESS'] %>
  ses_username: <%= ENV['SES_USERNAME'] %>
  ses_password: <%= ENV['SES_PASSWORD'] %>
  raven_url: <%= ENV['RAVEN_URL'] %>
  default_lang: <%= ENV['DEFAULT_LANG'] %>
  jwt:
    secret: <%= ENV['JWT_SECRET'] %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
  secret_key_base: test
  jwt:
    secret: 'secret'
